"""Added table 'donaters'

Revision ID: 97f0f6f81c42
Revises: 96c7bed77d3c
Create Date: 2026-07-07 12:37:01.295794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '97f0f6f81c42'
down_revision: Union[str, Sequence[str], None] = '96c7bed77d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donaters',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('plan_id', sa.BigInteger(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donaters')
    # ### end Alembic commands ###
